### ISSUE TITLE
Where does doc-view-roll-minor-mode come from?

### ISSUE THREAD

**Issue by Dima-369** [dalanicolai/image-roll.el#10]
The README lists `M-x doc-view-roll-minor-mode`, but `image-roll.el` does not define that function? Where is it coming from?

**Comment by dalanicolai** [comment]
There is a link to a modified doc-view file, which defines that function, right [in that same section](https://github.com/dalanicolai/image-roll.el#doc-view). However, for some reason, scrolling in doc-view is slow (it already is like that without using image-roll). So, I am creating a faster alternative to doc-view [here](https://github.com/dalanicolai/emacs-papyrus). Development is slow, because it takes a lot of (free) time, and so it only works for djvu files now. But if you are interested in continuous scroll for reading djvu files, then I would recommend using that package.

**Comment by Dima-369** [comment]
> There is a link to a modified doc-view file, which defines that function, right [in that same section](https://github.com/dalanicolai/image-roll.el#doc-view).

Ahhh, my bad, how did I miss that :(

I see, thanks for linking the `emacs-papyrus` repository. This looks interesting but in do not use `djvu` files (at least right now).
